/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrImportacion;
import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;

public class JDialogProcessImport extends javax.swing.JDialog implements ViewImportacion {

    private CtrImportacion ctr;
    
    public JDialogProcessImport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiar();
        jTextArea1.setBackground(getBackground());
        jTextArea1.setDisabledTextColor(Color.BLACK);
        this.setLocationRelativeTo(parent);
        this.getRootPane().setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY));
    }

    public void limpiar() {
        jTextArea1.setText("");
        jButton1.setVisible(false);
        jButton2.setVisible(false);
    }
    
    @Override
    public void setModo(int modo) {
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        
        switch (modo) {
            case MODO_SOBRESCRIBIR:
                jButton1.setText("Sobrescribir todo");
                jButton2.setText("Sobrescribir");
                jButton1.setActionCommand(CMD_SOBRESCRIBIR_TODO);
                jButton2.setActionCommand(CMD_SOBRESCRIBIR);
                break;
            case MODO_OMITIR:
                jButton1.setText("Omitir todo");
                jButton2.setText("Omitir");
                jButton1.setActionCommand(CMD_OMITIR_TODO);
                jButton2.setActionCommand(CMD_OMITIR);
                break;
            case MODO_MESSAGE:
                jButton2.setVisible(false);
                jButton1.setText("OK");
                jButton1.setActionCommand(CMD_OK);
        }
        
    }
    
    public void setVisible(boolean b, String format, File file) {
        ctr.iniciar(format, file);
        super.setVisible(true);
    }
    
    @Override
    public void setVisible(boolean b) {
         // do nothing
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(300, 175));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setEnabled(false);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jTextArea1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(CtrImportacion ctr) {
        jButton1.addActionListener(ctr);
        jButton2.addActionListener(ctr);
        this.ctr = ctr;
    }

    @Override
    public void setProgress(int p) {
        jProgressBar1.setValue(p);
    }

    @Override
    public void ocultar() {
        dispose();
    }

    @Override
    public void notificar(String msg) {
        jTextArea1.setText(msg);
    }

}
