/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.medidas.JPanelCurvas;
import vista.campanya.JPanelCampaña;
import vista.modulo.JPanelModulo;
import controlador.CtrAdminCampanyas;
import controlador.CtrAdminMedidas;
import controlador.CtrAdminModulos;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sergio
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    private JPanel [] paneles;
    private int nivel;
    private static final int MAX_LEVEL=5;
    
    public JFramePrincipal() {
       initComponents();
       nivel=0;
       
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception ex) {
            System.err.println("Error al cambiar de tema.");
        }
       //Paneles ordenados por niveles de la aplicación de la aplicación
       paneles= new JPanel[MAX_LEVEL];
       paneles[0]= new JPanelModulo(this);
       paneles[1]= new JPanelCampaña(this);
       paneles[2]= new JPanelCurvas(this);
       CtrAdminModulos ctrm = new CtrAdminModulos((ViewAdminModulos) paneles[0]);
       CtrAdminCampanyas ctrc = new CtrAdminCampanyas ((ViewAdminCampanya) paneles[1]);
       CtrAdminMedidas ctrme= new CtrAdminMedidas((ViewAdminMedidas) paneles[2]);
       ctrm.setCtrSiguiente(ctrc);
       ctrc.setCtrSiguiente(ctrme);
       ctrc.setCtrAnterior(ctrm);
       
       jPanelPrincipal.setLayout(new BorderLayout()); //Layout para poner las cosas en su lugar
       jPanelPrincipal.add(paneles[0]);
       // pack(); 
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelPrincipal = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(508, 349));

      javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
      jPanelPrincipal.setLayout(jPanelPrincipalLayout);
      jPanelPrincipalLayout.setHorizontalGroup(
         jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 488, Short.MAX_VALUE)
      );
      jPanelPrincipalLayout.setVerticalGroup(
         jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 327, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    public void siguientePanel(){
        int ant=nivel;
        nivel++;
        mostrarNivel(nivel,ant);
        
        
    }

    private void mostrarNivel(int sig,int ant) {
        jPanelPrincipal.remove(paneles[ant]);
        jPanelPrincipal.add(paneles[sig]);
        jPanelPrincipal.updateUI();
    }
    public void anteriorPanel(){
        int ant=nivel;
        nivel--;
        mostrarNivel(nivel,ant);
        
        
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel jPanelPrincipal;
   // End of variables declaration//GEN-END:variables
}
