/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.correccion;

import javax.swing.DefaultComboBoxModel;
import javax.swing.border.TitledBorder;
import modelo.Canal;
import modelo.CurvaMedida;
import modelo.MedidaCanal;

/**
 *
 * @author Vikour
 */
public class JPanelCanalCorreccion extends javax.swing.JPanel {

   private CurvaMedida curva;
   private int selected;
   private Canal [] canales;


   public JPanelCanalCorreccion() {
      initComponents();
   }
   
   public void setTituloBorde(String title) {
      ((TitledBorder) getBorder()).setTitle(title);
   }

   public void setCurva(CurvaMedida curva) {
      
      this.curva = curva;
      
      jComboBoxCanal.removeAllItems();      
      canales = curva.getCanales();
      
      for (Canal canal : canales)
         jComboBoxCanal.addItem(canal.toString());
      
      jComboBoxCanal.setSelectedIndex(0);


   }
   
   public MedidaCanal getMedidaCanalElegida() {
      return curva.getMedidaCanal(canales[selected]);
   }
   
   public double getNuevoValor() {
      return Double.valueOf(jTextFieldValorNuevo.getText());
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jComboBoxCanal = new javax.swing.JComboBox<>();
      jLabel2 = new javax.swing.JLabel();
      jTextFieldValorActual = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jTextFieldValorNuevo = new javax.swing.JTextField();

      setBorder(javax.swing.BorderFactory.createTitledBorder("titulo"));

      jLabel1.setText("Canal : ");

      jComboBoxCanal.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBoxCanalActionPerformed(evt);
         }
      });

      jLabel2.setText("Valor Actual : ");

      jTextFieldValorActual.setEditable(false);
      jTextFieldValorActual.setDisabledTextColor(new java.awt.Color(0, 0, 0));
      jTextFieldValorActual.setEnabled(false);
      jTextFieldValorActual.setFocusable(false);

      jLabel3.setText("Nuevo valor : ");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jComboBoxCanal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorActual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorNuevo)))
                  .addGap(150, 150, 150)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jComboBoxCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(jTextFieldValorActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jTextFieldValorNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(17, Short.MAX_VALUE))
      );

      layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxCanal, jTextFieldValorActual, jTextFieldValorNuevo});

   }// </editor-fold>//GEN-END:initComponents

   private void jComboBoxCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCanalActionPerformed
      selected = jComboBoxCanal.getSelectedIndex();
      Canal [] canales = curva.getCanales();
      jTextFieldValorActual.setText(curva.getMedidaCanal(canales[selected]).toString());
      jTextFieldValorNuevo.setText("");
   }//GEN-LAST:event_jComboBoxCanalActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox<String> jComboBoxCanal;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JTextField jTextFieldValorActual;
   private javax.swing.JTextField jTextFieldValorNuevo;
   // End of variables declaration//GEN-END:variables


}
