/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.correccion;

import java.util.ArrayList;
import java.util.List;
import modelo.ConfiguracionCorreccion;
import modelo.CurvaMedida;
import modelo.MedidaCanal;
import modelo.MetodoCorreccion;

/**
 *
 * @author Vikour
 */
public class JPanelCorreccionComun extends JPanelConfigCorreccion {

   private CurvaMedida curva;
   
   public JPanelCorreccionComun() {
      initComponents();
   }

   @Override
   public List<ConfiguracionCorreccion> getConfiguracionCorreccion() {
      List<ConfiguracionCorreccion> config = new ArrayList<>();
      MedidaCanal irradiancia = jPanelCanalCorreccionIrradiancia.getMedidaCanalElegida();
      MedidaCanal temperatura = jPanelCanalCorreccionTemperatura.getMedidaCanalElegida();
      double nuevaIrradiancia = jPanelCanalCorreccionIrradiancia.getNuevoValor();
      double nuevaTemperatura = jPanelCanalCorreccionTemperatura.getNuevoValor();
      
      ConfiguracionCorreccion correccion = new ConfiguracionCorreccion(irradiancia, temperatura, nuevaIrradiancia, nuevaTemperatura, curva);
      config.add(correccion);
      
      return config;
   }
   
   @Override
   public void setCurva(CurvaMedida original) {
      curva = original;
      jPanelCanalCorreccionIrradiancia.setTituloBorde("Irradiancia");
      jPanelCanalCorreccionTemperatura.setTituloBorde("Temperatura");
      jPanelCanalCorreccionIrradiancia.setCurva(original);
      jPanelCanalCorreccionTemperatura.setCurva(original);
   }
   
   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanelCanalCorreccionIrradiancia = new vista.correccion.JPanelCanalCorreccion();
      jPanelCanalCorreccionTemperatura = new vista.correccion.JPanelCanalCorreccion();

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanelCanalCorreccionIrradiancia, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
         .addComponent(jPanelCanalCorreccionTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanelCanalCorreccionIrradiancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanelCanalCorreccionTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
   }// </editor-fold>//GEN-END:initComponents


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private vista.correccion.JPanelCanalCorreccion jPanelCanalCorreccionIrradiancia;
   private vista.correccion.JPanelCanalCorreccion jPanelCanalCorreccionTemperatura;
   // End of variables declaration//GEN-END:variables



}
