/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.correccion;

import java.util.ArrayList;
import java.util.List;
import modelo.ConfiguracionCorreccion;
import modelo.CurvaMedida;
import modelo.MedidaCanal;
import modelo.Modulo;

/**
 *
 * @author Vikour
 */
public class JPanelCorreccionMetodo2 extends JPanelConfigCorreccion {

    private CurvaMedida curva;
    
    /**
     * Creates new form JPanelCorreccionMetodo1
     */
    public JPanelCorreccionMetodo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAlpha = new javax.swing.JTextField();
        jTextFieldBeta = new javax.swing.JTextField();
        jCheckBoxAlpha = new javax.swing.JCheckBox();
        jCheckBoxBeta = new javax.swing.JCheckBox();
        jCheckBoxRS = new javax.swing.JCheckBox();
        jCheckBoxKappa = new javax.swing.JCheckBox();
        jTextFieldRS = new javax.swing.JTextField();
        jTextFieldKappa = new javax.swing.JTextField();
        jTextFieldA = new javax.swing.JTextField();
        jCheckBoxA = new javax.swing.JCheckBox();
        jPanelCanalIrradiancia = new vista.correccion.JPanelCanalCorreccion();
        jPanelCanalTemperatura = new vista.correccion.JPanelCanalCorreccion();

        jLabel1.setText("Marca para almacenar los parámetros modificados:");

        jCheckBoxAlpha.setText("Alpha : ");
        jCheckBoxAlpha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAlphaActionPerformed(evt);
            }
        });

        jCheckBoxBeta.setText("Beta : ");

        jCheckBoxRS.setText("RS : ");

        jCheckBoxKappa.setText("Kappa : ");

        jCheckBoxA.setText("A :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxAlpha)
                            .addComponent(jCheckBoxBeta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxRS)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBeta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxKappa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldKappa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxAlpha)
                    .addComponent(jCheckBoxRS)
                    .addComponent(jTextFieldRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBeta)
                    .addComponent(jCheckBoxKappa)
                    .addComponent(jTextFieldKappa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCanalIrradiancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCanalTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCanalIrradiancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCanalTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxAlphaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAlphaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxAlphaActionPerformed

    @Override
    public List<ConfiguracionCorreccion> getConfiguracionCorreccion() {
        Modulo modulo = curva.getModulo();
        List<ConfiguracionCorreccion> config = new ArrayList<>();
        
        if (jCheckBoxAlpha.isSelected())
            modulo.setAlpha(Double.valueOf(jTextFieldAlpha.getText()));
        
        if (jCheckBoxBeta.isSelected())
            modulo.setBeta(Double.valueOf(jTextFieldBeta.getText()));
        
        if (jCheckBoxRS.isSelected())
            modulo.setRs(Double.valueOf(jTextFieldRS.getText()));
        
        if (jCheckBoxKappa.isSelected())
            modulo.setKappa(Double.valueOf(jTextFieldKappa.getText()));
        
        if (jCheckBoxA.isSelected())
            modulo.setA(Double.valueOf(jTextFieldA.getText()));

        MedidaCanal irradiancia = jPanelCanalIrradiancia.getMedidaCanalElegida();
        MedidaCanal temperatura = jPanelCanalTemperatura.getMedidaCanalElegida();
        double nuevaIrradiancia = jPanelCanalIrradiancia.getNuevoValor();
        double nuevaTemperatura = jPanelCanalTemperatura.getNuevoValor();
      
        ConfiguracionCorreccion correccion = new ConfiguracionCorreccion(irradiancia, temperatura, nuevaIrradiancia, nuevaTemperatura, curva);
        correccion.setAlpha(Double.valueOf(jTextFieldAlpha.getText()));
        correccion.setBeta(Double.valueOf(jTextFieldBeta.getText()));
        correccion.setKappa(Double.valueOf(jTextFieldRS.getText()));
        correccion.setRs(Double.valueOf(jTextFieldKappa.getText()));
        correccion.setA(Double.valueOf(jTextFieldA.getText()));
        config.add(correccion);

        return config;
    }

    @Override
    public void setCurva(CurvaMedida original) {
        Modulo modulo = original.getModulo();
        
        curva = original;
        jPanelCanalIrradiancia.setTituloBorde("Irradiancia");
        jPanelCanalIrradiancia.setCurva(original);
        jPanelCanalTemperatura.setTituloBorde("Temperatura");
        jPanelCanalTemperatura.setCurva(original);
        jTextFieldAlpha.setText(String.valueOf(modulo.getAlpha()));
        jTextFieldBeta.setText(String.valueOf(modulo.getBeta()));
        jTextFieldKappa.setText(String.valueOf(modulo.getKappa()));
        jTextFieldRS.setText(String.valueOf(modulo.getRs()));
        jTextFieldA.setText(String.valueOf(modulo.getA()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxA;
    private javax.swing.JCheckBox jCheckBoxAlpha;
    private javax.swing.JCheckBox jCheckBoxBeta;
    private javax.swing.JCheckBox jCheckBoxKappa;
    private javax.swing.JCheckBox jCheckBoxRS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private vista.correccion.JPanelCanalCorreccion jPanelCanalIrradiancia;
    private vista.correccion.JPanelCanalCorreccion jPanelCanalTemperatura;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldAlpha;
    private javax.swing.JTextField jTextFieldBeta;
    private javax.swing.JTextField jTextFieldKappa;
    private javax.swing.JTextField jTextFieldRS;
    // End of variables declaration//GEN-END:variables
}
