/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Grafica;

import java.awt.event.ActionListener;

/**
 *
 * @author Elias
 */
public class JPanelToggleButtonsIV_PV extends javax.swing.JPanel {

    public JPanelToggleButtonsIV_PV() {
        initComponents();
        jToggleButtonIV.setSelected(true);
    }
    
    public boolean isSelectedIV() {
        return jToggleButtonIV.isSelected();
    }
    
    public boolean isSelectedPV() {
        return jToggleButtonPV.isSelected();
    }
    
    public void setController(ActionListener controller, String cmd_iv, String cmd_pv) {
        jToggleButtonIV.setActionCommand(cmd_iv);
        jToggleButtonIV.addActionListener(controller);
        jToggleButtonPV.setActionCommand(cmd_pv);
        jToggleButtonPV.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonIV = new javax.swing.JToggleButton();
        jToggleButtonPV = new javax.swing.JToggleButton();

        jToggleButtonIV.setText("I-V");
        jToggleButtonIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonIVActionPerformed(evt);
            }
        });

        jToggleButtonPV.setText("P-V");
        jToggleButtonPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButtonIV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonPV))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jToggleButtonIV)
                .addComponent(jToggleButtonPV))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPVActionPerformed
        jToggleButtonIV.setSelected(false);
        jToggleButtonPV.setSelected(true);
    }//GEN-LAST:event_jToggleButtonPVActionPerformed

    private void jToggleButtonIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonIVActionPerformed
        jToggleButtonIV.setSelected(true);
        jToggleButtonPV.setSelected(false);
    }//GEN-LAST:event_jToggleButtonIVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButtonIV;
    private javax.swing.JToggleButton jToggleButtonPV;
    // End of variables declaration//GEN-END:variables
}
